#!/bin/sh
# android gcc wrapper

if [ -z "${NDK}" ]; then
	NDK=~/Downloads/android-ndk-r10e
	echo "Using ${NDK} as NDK path."
	if [ ! -d "${NDK}" ]; then
		echo "Invalid path in NDK environment, please change me."
		exit 1
	fi
fi

if [ -n "${NDK_ARCH}" ]; then
	ARCH=${NDK_ARCH}
else
	ARCH=mips
	ARCH=x86
	ARCH=arm
	ARCH=x86_64
	ARCH=aarch64
fi

ANDROID_API_LEVEL=$1
shift

echo "Using NDK ${NDK}"
echo "Using NDK_ARCH ${NDK_ARCH} -> ${ARCH}"
echo "Using ANDROID_API_LEVEL ${ANDROID_API_LEVEL}"

#------------------------------------------#

PROGDIR="$(dirname "$0")"
PROGDIR="$(cd "$PROGDIR" && pwd)"

OS="$(uname | tr 'A-Z' 'a-z')"
[ "${OS}" = macos ] && OS=darwin

ARCH2=${ARCH}
case "${ARCH}" in
aarch64)
	NDKPFX=${ARCH}-linux-android
	ARCH2=arm64
	;;
arm)
	NDKPFX=${ARCH}-linux-androideabi
	;;
mips)
	NDKPFX=mipsel-linux-android
	${NDKPFX}-gcc 2>/dev/null
	if [ $? -gt 1 ]; then
		NDKPFX=mipsel-linux-android
	fi
	;;
mips64)
	NDKPFX=mips64el-linux-android
	${NDKPFX}-gcc 2>/dev/null
	if [ $? -gt 1 ]; then
		NDKPFX=mips64el-linux-android
	fi
	;;
x86)
	NDKPFX=i686-android-linux
	${NDKPFX}-gcc 2>/dev/null
	if [ $? -gt 1 ]; then
		NDKPFX=i686-linux-android
	fi
	;;
x86_64)
	NDKPFX=x86_64-android-linux
	${NDKPFX}-gcc 2>/dev/null
	if [ $? -gt 1 ]; then
		NDKPFX=x86_64-linux-android
	fi
	;;
esac

PROGDIR=${NDK}
PLATFORM=android-${ANDROID_API_LEVEL}
PLATFORM_ROOT=${PROGDIR}/platforms/${PLATFORM}/arch-${ARCH2}
PLATFORM_PATH=${PLATFORM_ROOT}/usr

NDK_BINS=$(ls "${PROGDIR}"/toolchains/*/prebuilt/"${OS}"*/bin |grep prebuilt | grep "/${ARCH}-" |sort |tail -n 1)
[ -z "${NDK_BINS}" ] && \
NDK_BINS=$(ls "${PROGDIR}"/toolchains/*/prebuilt/"${OS}"*/bin |grep prebuilt | grep "/${ARCH}" |sort |tail -n 1)

if [ -z "${NDK_BINS}" ]; then
	echo "Cant find NDK_BINS"
	exit 1
fi
CFLAGS="${CFLAGS} --sysroot=${PLATFORM_ROOT}"
CFLAGS="${CFLAGS} -fPIC -fPIE -pie"

case "${ARCH}" in
mips64)
	LDFLAGS=-L${PLATFORM_PATH}/lib64
	;;
*)
	LDFLAGS=-L${PLATFORM_PATH}/lib
	;;
esac

LDFLAGS="${LDFLAGS} --sysroot=${PLATFORM_ROOT}"

CC="${NDKPFX}-gcc"
AR="${NDKPFX}-ar"
EXT_SO=so

export PATH="${NDK_BINS}:$PATH"
export EXT_SO AR CC CFLAGS LDFLAGS PATH

echo ${CC} ${LDFLAGS} ${CFLAGS} $*
${CC} ${LDFLAGS} ${CFLAGS} $*
